# Generated by Django 4.2.2 on 2023-06-23 08:13

import cabinet.models.file
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'компетенция',
                'verbose_name_plural': 'компетенции',
                'db_table': 'competence',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Сотрудник принял приглашение?')),
                ('is_entry', models.BooleanField(default=False, verbose_name='Это заявка на вступление?')),
            ],
            options={
                'verbose_name': 'участник',
                'verbose_name_plural': 'участники',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=150, verbose_name='Название проекта')),
                ('description', models.TextField(help_text='Несколько предложений', verbose_name='Описание проекта')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Проект архивирован?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('permissions', models.JSONField(verbose_name='Набор флагов доступа')),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.role', verbose_name='Родитель')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'роли',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('start', models.DateField(verbose_name='Начало')),
                ('end', models.DateField(verbose_name='Конец')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.sprint', verbose_name='Родитель')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'спринт',
                'verbose_name_plural': 'спринты',
                'db_table': 'sprint',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in-progress', 'В работе'), ('pause', 'В паузе'), ('stop', 'В стопе'), ('ready', 'Готово'), ('closed', 'Закрыта')], max_length=14, verbose_name='Статус')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('checked_date', models.DateField(verbose_name='Дата проверки')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabinet.member', verbose_name='На кого назначена')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.task', verbose_name='Родительская')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.project', verbose_name='Проект')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.sprint', verbose_name='Спринт')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='UserCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.competence', verbose_name='Компетенция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'связь компетенции и пользователя',
                'verbose_name_plural': 'связи компетенций и пользователей',
                'db_table': 'user_competence',
            },
        ),
        migrations.CreateModel(
            name='TaskWorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.CharField(max_length=150, verbose_name='Описание работ')),
                ('hours', models.FloatField(default=0, verbose_name='Затраченные на работу часы')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кто списал')),
            ],
            options={
                'verbose_name': 'списание времени в задаче',
                'verbose_name_plural': 'списания времени в задачах',
                'db_table': 'task_work_time',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('message', models.CharField(max_length=150, verbose_name='Комментарий')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.taskcomment', verbose_name='Родитель')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'комментарий к задаче',
                'verbose_name_plural': 'комментарии к задачам',
                'db_table': 'task_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.competence', verbose_name='Компетенция')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.project', verbose_name='Проект')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.role', verbose_name='Роль на проекте')),
            ],
            options={
                'verbose_name': 'связь компетенции и роли',
                'verbose_name_plural': 'связи компетенций и ролей',
                'db_table': 'role_competence',
            },
        ),
        migrations.CreateModel(
            name='ProjectLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время события')),
                ('object_id', models.IntegerField(default=0, verbose_name='ID объекта')),
                ('name', models.CharField(max_length=150, verbose_name='Название действия')),
                ('fields', models.JSONField(blank=True, null=True)),
                ('action_flag', models.PositiveSmallIntegerField(choices=[(1, 'Создано'), (2, 'Изменено'), (3, 'Удалено')], default=1, verbose_name='Тип события')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип сущности')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
                'db_table': 'project_log_entry',
                'ordering': ['action_time'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to=cabinet.models.file.directory_path, verbose_name='Файл')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Файл архивирован?')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.taskcomment', verbose_name='Комментарий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.project', verbose_name='Проект')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.task', verbose_name='Задача')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто залил')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
                'db_table': 'file',
            },
        ),
    ]
