from .authentication import CustomAuthenticationForm
from .password_change import CustomPasswordChangeForm
from .password_reset import CustomPasswordResetForm
from .registration import CustomRegistrationForm
